@startuml
interface iSmartPhone {
    # PhoneNumber : string <<get>> <<set>>
    # OwnerName : string <<get>> <<set>>
    + getOS() : string
}
class Program {
    {static} Main(args:string[]) : void
}
@enduml
